In [4]:
import time
from nearpy import Engine
from nearpy.hashes import RandomBinaryProjections
import numpy
from nearpy.filters import NearestFilter
from nearpy.distances import CosineDistance
# Dimension of our vector space
dimension = 512

# Create a random binary hash with 10 bits
rbp = RandomBinaryProjections('rbp', 4)

# Create engine with pipeline configuration
engine = Engine(dimension, lshashes=[rbp], vector_filters=[NearestFilter(40)])
# 计算目标图片与数据库中每张图像的余弦相似度
def ann_nearpy(query, features): 
    for i in range(len(features)):
        engine.store_vector(features[i], i)
    return engine.neighbours(query)

In [15]:
dir(numpy)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [5]:
features = []
for i in range(50000):
    vector = numpy.random.rand((512))
    features.append(i)

In [6]:
feature = numpy.random.rand((512))

In [8]:
rbp.hash_vector(feature)

['1010']

In [17]:
len(features)

50000

In [18]:
features[0]

0

## 官方示例

In [20]:
import numpy

from nearpy import Engine
from nearpy.hashes import RandomBinaryProjections
from nearpy.filters import NearestFilter
from nearpy.distances import CosineDistance
import time

In [20]:
# Dimension of our vector space
dimension = 512

# Create a random binary hash with 10 bits
rbp1 = RandomBinaryProjections('rbp', 6)
rbp2 = RandomBinaryProjections('rbp', 6)
rbp3 = RandomBinaryProjections('rbp', 6)

# Create engine with pipeline configuration
engine = Engine(dimension, lshashes=[rbp1,rbp2,rbp3], distance = CosineDistance(), vector_filters=[NearestFilter(40)])

# Index 1000000 random vectors (set their data to a unique string)
for index in range(400):
    v = numpy.random.randn(dimension)
    engine.store_vector(v, index)

# Create random query vector
query = numpy.random.randn(dimension)

time_start = time.time()
# Get nearest neighbours
N = engine.neighbours(query)
time_end = time.time()
print('Time cost = %fs' % (time_end - time_start))

Time cost = 0.000981s


In [21]:
len(N)

40

In [27]:
## 记录 d:512   top:10   num:100000
hash_bits:
0：  Time cost = 0.341805s
1:   Time cost = 0.314434s
2:   Time cost = 0.091795s 
3:   Time cost = 0.043913s
4:   Time cost = 0.027316s
5:   Time cost = 0.017579s
6:   Time cost = 0.005858s
7:   Time cost = 0.003906s
8:   Time cost = 0.000978s

4

In [28]:
N

[(array([ 0.06174992, -0.4954108 , -0.86069678,  0.09978044]),
  'data_9',
  0.4108251877338883),
 (array([-0.13733657, -0.84886094, -0.46537102,  0.20977034]),
  'data_8',
  0.4386866680924487),
 (array([-0.4020334 , -0.60883181,  0.52227861, -0.44149522]),
  'data_6',
  0.7675152362654372),
 (array([ 0.00216687,  0.34843457, -0.93560442, -0.05685972]),
  'data_4',
  0.92929474081039)]

In [29]:
query

array([ 0.72547481, -0.95382734, -0.4237912 , -0.58300637])

In [30]:
# 封装距离比较函数
def similarity_of_two(img_data1, img_data2):
    out = (img_data1*img_data2)
    return out.sum()

In [31]:
similarity_of_two(query, N[0][0])

0.8239174653076147

In [32]:
similarity_of_two(query, N[1][0])

0.7849552425533014

In [ ]:
CosineDistance()