In [1]:
import torch

In [7]:
o = torch.rand(1,3,7,7)

In [19]:
x = torch.rand(1,1,7,7)

In [23]:
x = torch.zeros(1,1,7,7)
x

tensor([[[[0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.]]]])

In [24]:
x.clamp(min=eps)

tensor([[[[1.0000e-06, 1.0000e-06, 1.0000e-06, 1.0000e-06, 1.0000e-06,
           1.0000e-06, 1.0000e-06],
          [1.0000e-06, 1.0000e-06, 1.0000e-06, 1.0000e-06, 1.0000e-06,
           1.0000e-06, 1.0000e-06],
          [1.0000e-06, 1.0000e-06, 1.0000e-06, 1.0000e-06, 1.0000e-06,
           1.0000e-06, 1.0000e-06],
          [1.0000e-06, 1.0000e-06, 1.0000e-06, 1.0000e-06, 1.0000e-06,
           1.0000e-06, 1.0000e-06],
          [1.0000e-06, 1.0000e-06, 1.0000e-06, 1.0000e-06, 1.0000e-06,
           1.0000e-06, 1.0000e-06],
          [1.0000e-06, 1.0000e-06, 1.0000e-06, 1.0000e-06, 1.0000e-06,
           1.0000e-06, 1.0000e-06],
          [1.0000e-06, 1.0000e-06, 1.0000e-06, 1.0000e-06, 1.0000e-06,
           1.0000e-06, 1.0000e-06]]]])

In [15]:
p = 3
eps=1e-6
x.clamp(min=eps).pow(p)

tensor([[[[1.0033e-01, 8.8227e-01, 5.7419e-03, 5.5655e-03, 4.3437e-01,
           9.0798e-01, 4.9242e-01],
          [3.1703e-01, 3.2315e-03, 6.2047e-02, 5.6418e-02, 1.4599e-01,
           5.5079e-03, 5.9872e-01],
          [8.2504e-01, 6.6977e-04, 9.0700e-02, 1.6446e-02, 3.1078e-01,
           5.9050e-01, 8.9840e-01],
          [9.0858e-02, 5.6157e-01, 5.4433e-01, 2.2653e-01, 6.8184e-01,
           9.9168e-03, 9.5171e-02],
          [1.2508e-01, 7.7442e-04, 2.0399e-03, 5.2763e-04, 9.8756e-03,
           3.6010e-04, 9.5143e-04],
          [2.2666e-01, 2.2885e-02, 9.9752e-01, 3.2545e-01, 1.3804e-04,
           1.7704e-01, 5.6846e-01],
          [1.2357e-02, 1.5098e-02, 9.4491e-01, 6.7785e-01, 4.5893e-02,
           5.9837e-06, 5.5216e-01]]]])